# -*- coding: utf-8 -*-
"""AA-Kompar-MPI-24-059-Lugie.p

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNgoGhpx6zkPA2sBJfITm_W8-7G5x0Nr
"""

!apt-get install libopenmpi-dev
!pip install mpi4py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mpi_lugi.py
# from mpi4py import MPI
# import time
# 
# comm = MPI.COMM_WORLD
# rank = comm.Get_rank()
# size = comm.Get_size()
# 
# if rank == 0:
#     print(f"Program dimulai dengan {size} proses secara paralel.\n")
# 
# print(f"Proses Rank {rank}: Sedang mengerjakan tugas...")
# time.sleep(1)
# 
# comm.Barrier()
# 
# if rank == 0:
#     print("\nSemua proses telah JOIN kembali ke alur utama.")
#     print("Tugas Selesai.")

!mpirun --allow-run-as-root --oversubscribe -n 4 python mpi_lugi.py